services:
  pg:
    image: postgres:16
    container_name: pg
    env_file:
      - .penv
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready  -U admin -d admin"]
      interval: 1s
      retries: 5
  rds:
    image: redis:alpine
    container_name: rds
    env_file:
      - .renv
    ports:
      - "6379:6379"
    volumes:
      - rds:/data
    healthcheck:
      test: ["CMD-SHELL","redis-cli","ping"]
      interval: 1s
      retries: 5

volumes:
  pg:
  rds:
